

const cityBreaksData = [
  {
    id: "cb-01",
    title: "CATACOMBS IN PARIS",
    category: "City Breaks",
    image: "imgs/holidays/inc/catacombs-paris.jpg",
    rating: 5,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 341,
    shortDesc: "Uncover the mysterious underground side of the City of Light with an exclusive tour of Paris's historic catacombs. Walk through hauntingly beautiful ossuaries holding centuries of history hidden beneath the bustling Parisian streets. Perfect for history buffs and travelers seeking a thrilling, unconventional urban adventure."
  },
  {
    id: "cb-02",
    title: "AMSTERDAM LIGHT FESTIVAL",
    category: "City Breaks",
    image: "imgs/holidays/inc/amsterdam-light-festival.jpg",
    rating: 4,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 259,
    shortDesc: "Experience the magic of Amsterdam as the city's iconic canals transform into an open-air light art gallery. Enjoy a cozy evening boat cruise to view breathtaking, illuminated installations designed by international artists. This seasonal winter getaway offers a vibrant, artistic perspective on a classic European destination."
  },
  {
    id: "cb-03",
    title: "KIEV WITH CHERNOBYL",
    category: "City Breaks",
    image: "imgs/holidays/inc/kiev-chernobyl.jpg",
    rating: 4,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 279,
    shortDesc: "Embark on an unforgettable journey blending the rich cultural heritage of Ukraine's capital with a historic tour of Chernobyl. Explore Kiev's golden-domed cathedrals and vibrant local markets before heading to the haunting, frozen-in-time exclusion zone of Pripyat. An exceptional choice for dark tourism enthusiasts and modern history lovers."
  },
  {
    id: "cb-04",
    title: "ICELAND W BLUE LAGOON",
    category: "City Breaks",
    image: "imgs/holidays/inc/iceland-blue-lagoon.jpg",
    rating: 4,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 229,
    shortDesc: "Escape to the dramatic landscapes of Iceland for a perfect mix of volcanic exploration and ultimate relaxation. Soak your worries away in the milky-blue, mineral-rich geothermal waters of the world-famous Blue Lagoon. Spend your nights hunting for the ethereal Northern Lights across Reykjavik's crisp, dark skies."
  },
  {
    id: "cb-05",
    title: "DRACULA'S CASTLE ROMANIA",
    category: "City Breaks",
    image: "imgs/holidays/inc/draculas-castle.jpg",
    rating: 4,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 229,
    shortDesc: "Step into a world of gothic legends and medieval charm with a trip deep into the mist-shrouded forests of Transylvania. Tour the imposing stone towers of Bran Castle, famously known as the inspiration behind Bram Stoker's Dracula. Discover cobblestone fortresses, local folklore, and stunning mountain backdrops."
  },
  {
    id: "cb-06",
    title: "SZECHENYI SPA BUDAPEST",
    category: "City Breaks",
    image: "imgs/holidays/inc/szechenyi-spa-budapest.jpg",
    rating: 5,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 129,
    shortDesc: "Relax like royalty in the 'City of Spas' with a visit to Europe's largest medicinal bath complex. Dive into the warm, healing outdoor thermal pools of Szechenyi, surrounded by magnificent Neo-Baroque architecture. A perfect city break to unwind, rejuvenate, and experience Budapest's rich café culture and nightlife."
  },
  {
    id: "cb-07",
    title: "ROME CITY BREAK",
    category: "City Breaks",
    image: "imgs/holidays/inc/rome-city-break.jpg",
    rating: 5,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 139,
    shortDesc: "Immerse yourself in thousands of years of living history, ancient monuments, and world-class culinary delights. Walk in the footsteps of gladiators at the Colosseum, marvel at the Vatican, and toss a coin into the Trevi Fountain. This fast-paced Roman escape serves as the ultimate destination for art and food lovers."
  },
  {
    id: "cb-08",
    title: "SWITZERLAND",
    category: "SWITZERLAND GENEVA",
    image: "imgs/holidays/inc/switzerland.jpg",
    rating: 5,
    duration: "5 Nights",
    features: ["Classic Room", "Flights included"],
    trustpilotScore: 4,
    price: 299,
    shortDesc: "Indulge in a premium lakeside escape surrounded by the snow-capped majesty of the Swiss Alps. Explore Geneva's sophisticated old town, iconic Jet d'Eau water fountain, and legendary watchmaking boutiques. Stay in a luxurious classic room with easy access to pristine nature and alpine mountain excursions."
  }
];

const inclusiveHolidaysData = [
  {
    id: "inc-01",
    title: "BEACHFRONT HOLIDAY IN ANTALYA",
    category: "Inclusive Holidays",
    image: "imgs/holidays/inc/antalyia.jpg",
    rating: 5,
    duration: "7 Nights",
    features: ["Flights included"],
    trustpilotScore: 4, 
    price: 399,
    shortDesc: "Escape to the beautiful Turkish Riviera for a week of pure sun-soaked bliss along Antalya's golden coast. Relax at a premium beachfront resort, swim in crystal-clear turquoise waters, and sample exquisite Mediterranean cuisine. This perfect coastal getaway effortlessly balances deep relaxation with vibrant local culture."
  },
  {
    id: "inc-02",
    title: "SIYAM WORLD MALDIVES",
    category: "All Inclusive",
    image: "imgs/holidays/inc/maldives.jpg",
    rating: 5,
    duration: "7 Nights", 
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 2049,
    shortDesc: "Indulge in a premium, worry-free island getaway at an expansive five-star playground in the heart of the Maldives. Stay in an overwater villa complete with private slides, dine across diverse global restaurants, and enjoy endless ocean water sports. The ultimate luxury retreat tailored for families, couples, and ocean adventurers alike."
  },
  {
    id: "inc-03",
    title: "ALL INCLUSIVE DUBAI",
    category: "Inclusive Deal",
    image: "imgs/holidays/inc/dubai.jpg",
    rating: 5,
    duration: "5 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 899,
    shortDesc: "Experience the ultimate fusion of futuristic city skylines and pristine, high-end desert beach luxury. This curated package covers top-tier accommodation, fine dining options, and seamless flights to the Middle East's entertainment capital. Ideal for travelers looking to explore towering skyscrapers, mega malls, and pristine beach clubs."
  },
  {
    id: "inc-04",
    title: "HARD ROCK CANCUN",
    category: "All Inclusive",
    image: "imgs/holidays/inc/cancun-hardrock.jpg",
    rating: 5,
    duration: "7 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 1499,
    shortDesc: "Live like a rock star at this high-energy, all-inclusive beachfront oasis fronting the majestic Caribbean Sea. Enjoy world-class live entertainment, celebrity-style amenities, expansive pool parties, and exceptional international dining choices. A thrilling tropical getaway designed for those who love great music and a lively resort atmosphere."
  },
  {
    id: "inc-05",
    title: "HYATT ZILARA CAP CANA",
    category: "All Inclusive",
    image: "imgs/holidays/inc/cap-cana.jpg",
    rating: 5,
    duration: "10 Nights", 
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 1319,
    shortDesc: "Immerse yourself in an exclusive, adults-only paradise nestled along the clear waters of Juanillo Beach. This extended 10-night escape offers infinity pools, a water park, a world-class fitness center, and stunning oceanfront views. Perfect for travelers seeking a sophisticated, peaceful sanctuary with top-tier hospitality."
  },
  {
    id: "inc-06",
    title: "SAN ANTONIO HOTEL MALTA",
    category: "All Inclusive",
    image: "imgs/holidays/inc/malta.jpg",
    rating: 5,
    duration: "4 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 269,
    shortDesc: "Discover the historic charm and scenic beauty of the Mediterranean with a Moorish-style resort stay in St. Paul's Bay. Unwind at the rooftop infinity pool, treat yourself at the Moroccan-themed spa, and enjoy diverse buffet dining. A budget-friendly, highly rated escape ideal for exploring ancient architecture and sunny coasts."
  },
  {
    id: "inc-07",
    title: "TURKEY HOLIDAYS",
    category: "Turkey Holidays",
    image: "imgs/holidays/inc/turkey.jpg",
    rating: 5,
    duration: "05 Nights", 
    features: ["01 Hotel Stay", "Flights included"],
    trustpilotScore: 4,
    price: 399,
    shortDesc: "Unpack the rich history, lively bazaars, and scenic landscapes of Turkey on this beautifully balanced short escape. Benefit from a seamless hotel stay, centrally located to give you easy access to iconic landmarks, spice markets, and local cafes. A fantastic choice for culture seekers looking to maximize a five-night travel itinerary."
  },
  {
    id: "inc-08",
    title: "CANCUN",
    category: "Cancun Special Holidays",
    image: "imgs/holidays/inc/cancun-special.jpg",
    rating: 4, 
    duration: "7 Nights",
    features: ["Luxury Resort", "Flights included"],
    trustpilotScore: 4,
    price: 1499,
    shortDesc: "Treat yourself to a signature Mexican Caribbean experience at a handpicked, luxury beachfront resort. Spend your days relaxing under swaying palm trees, exploring nearby Mayan ruins, or diving into crystal-clear cenotes. This special holiday package delivers an exceptional blend of cultural exploration and premium beach relaxation."
  }
];

const BeachHolidays = [
  {
    id: "bch-01",
    title: "SOFITEL THE PALM DUBAI",
    category: "Beach Holiday",
    shortDesc: "Experience a premium luxury getaway at this Polynesian-style island resort. Enjoy pristine private beaches, relaxing spa treatments, and world-class seaside dining.",
    image: "imgs/holidays/inc/sofitel-palm-dubai.jpg",
    rating: 5,
    duration: "5 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 799,
  },
  {
    id: "bch-02",
    title: "HARD ROCK BALI",
    category: "Beach Holidays",
    shortDesc: "Dive into a vibrant beachfront experience packed with energy, live music, and entertainment. Perfect for travelers seeking a lively tropical escape right on Kuta Beach.",
    image: "imgs/holidays/inc/hard-rock-bali.jpg",
    rating: 5,
    duration: "7 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 899,
  },
  {
    id: "bch-03",
    title: "MALDIVIAN DREAM IN CRETE",
    category: "Beach Holidays",
    shortDesc: "Immerse yourself in crystal-clear waters and luxurious overwater-style vibes in Greece. Experience a perfect blend of Mediterranean charm and exotic island luxury.",
    image: "imgs/holidays/inc/maldivian-dream-crete.jpg",
    rating: 5,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 899,
  },
  {
    id: "bch-04",
    title: "ATLANTIS THE PALM DUBAI",
    category: "Beach Holidays",
    shortDesc: "Discover an iconic oceanfront paradise featuring legendary water parks and underwater aquariums. Indulge in ultra-luxury amenities on the crescent of the Palm Jumeirah.",
    image: "imgs/holidays/inc/atlantis-palm-dubai.jpg",
    rating: 5,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 899,
  },
  {
    id: "bch-05",
    title: "TRUE BLUE BAY GRENADA",
    category: "Beach Holidays",
    shortDesc: "Relax at a charming, eco-friendly boutique resort overlooking the sparkling blue waters. Unwind with authentic Caribbean hospitality, water sports, and wellness activities.",
    image: "imgs/holidays/inc/true-blue-bay-grenada.jpg",
    rating: 5,
    duration: "7 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 959,
  },
  {
    id: "bch-06",
    title: "CATACOMBS IN PARIS",
    category: "Beach Holidays",
    shortDesc: "Uncover the mysterious underground history of the City of Light on an exclusive tour. Walk through hauntingly beautiful historic ossuaries hidden right beneath the streets.",
    image: "imgs/holidays/inc/catacombs-paris.jpg",
    rating: 5,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 999,
  },
  {
    id: "bch-07",
    title: "JUMEIRAH ZABEEL SARAY",
    category: "Beach Holidays",
    shortDesc: "Step into an opulent palace inspired by the majestic grandeur of the Ottoman Empire. Enjoy lavish coastal living, private beach access, and premium spa facilities.",
    image: "imgs/holidays/inc/jumeirah-zabeel-saray.jpg",
    rating: 5,
    duration: "5 Nights",
    features: ["Superior King Room", "Flights included"],
    trustpilotScore: 4,
    price: 1199,
  },
  {
    id: "bch-08",
    title: "PHUKET AND KHAO LAK",
    category: "Beach Holidays",
    shortDesc: "Combine vibrant island entertainment with tranquil, untouched sandy coastlines. Experience the absolute best of Southern Thailand in one ultimate multi-stop escape.",
    image: "imgs/holidays/inc/phuket-khao-lak.jpg",
    rating: 5,
    duration: "10 Nights",
    features: ["1X Hotel Stay", "Flights included"],
    trustpilotScore: 4,
    price: 1349,
  },
  {
    id: "bch-09",
    title: "JEWEL OF THAILAND",
    category: "Beach Holidays",
    shortDesc: "Journey from bustling city temples to dramatic limestone cliffs and serene shores. The ultimate triple-destination tropical tour covering Thailand's iconic highlights.",
    image: "imgs/holidays/inc/jewel-of-thailand.jpg",
    rating: 5,
    duration: "10 Nights",
    features: ["1x Deluxe Garden View Room", "Flights included"],
    trustpilotScore: 4,
    price: 1419,
  },
  {
    id: "bch-10",
    title: "RETREAT THE PALM",
    category: "Beach Holidays",
    shortDesc: "Rejuvenate your body and mind at Dubai's premier holistic beach wellness sanctuary. Enjoy a peaceful oceanfront stay focused on relaxation, healthy living, and comfort.",
    image: "imgs/holidays/inc/retreat-the-palm.jpg",
    rating: 5,
    duration: "5 Nights",
    features: ["1x Deluxe King Room", "Flights included"],
    trustpilotScore: 4,
    price: 889,
  }
];





const FamilyHolidays = [
  {
    id: "fam-01",
    title: "HURGHADA AQUA PARK",
    category: "FAMILY_HOLIDAY",
    shortDesc: "Make unforgettable family memories at this spectacular Red Sea waterpark resort. Enjoy thrilling water slides, kids clubs, and beautiful sunny beach activities.",
    image: "imgs/holidays/inc/hurghada-aqua-park.jpg",
    rating: 5,
    duration: "7 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 378,
  },
  {
    id: "fam-02",
    title: "ATLANTIS FAMILY GETAWAY",
    category: "FAMILY_HOLIDAY",
    shortDesc: "Take your family on a legendary getaway to Dubai's ultimate oceanfront playground. Experience access to marine aquariums, waterparks, and premium beachfront dining.",
    image: "imgs/holidays/inc/atlantis-family-getaway.jpg",
    rating: 5,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 693,
  },
  {
    id: "fam-03",
    title: "HARD ROCK BALI",
    category: "FAMILY_HOLIDAY",
    shortDesc: "Rock your family vacation at this energetic, music-themed beachfront sanctuary. Packed with large lagoon pools, daily kids activities, and live family entertainment.",
    image: "imgs/holidays/inc/hard-rock-bali1.jpg",
    rating: 5,
    duration: "7 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 897,
  },
  {
    id: "fam-04",
    title: "UNIVERSAL ORLANDO",
    category: "FAMILY_HOLIDAY",
    shortDesc: "Step directly into the action at the world's premier theme park capital. Uncover magic and adventure across immersive cinematic lands perfect for all ages.",
    image: "imgs/holidays/inc/universal-orlando.jpg",
    rating: 5,
    duration: "14 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 1395,
  },
  {
    id: "fam-05",
    title: "SIYAM WORLD FAMILY GETAWAY",
    category: "FAMILY_HOLIDAY",
    shortDesc: "Reinvent island luxury with an endless array of fun activities in the Maldives. Features an overwater open-air waterpark, expansive family villas, and pristine shores.",
    image: "imgs/holidays/inc/siyam-world-family.jpg",
    rating: 5,
    duration: "7 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 1770,
  },
  {
    id: "fam-06",
    title: "SUN SIYAM VILU REEF FAMILY GETAWAY",
    category: "FAMILY_HOLIDAY",
    shortDesc: "Relax in a boutique tropical haven blessed with crystalline water lagoons. Indulge in cozy family beach chalets, watersports, and genuine island hospitality.",
    image: "imgs/holidays/inc/sun-siyam-vilu-reef.jpg",
    rating: 5,
    duration: "7 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 1450,
  },
  {
    id: "fam-07",
    title: "DB SEABANK RESORT MALTA",
    category: "FAMILY_HOLIDAY",
    shortDesc: "Enjoy a stress-free Mediterranean escape at Malta's leading family resort. Located right by Mellieha Bay, offering themed restaurants and multiple lagoon pools.",
    image: "imgs/holidays/inc/db-seabank-malta.jpg",
    rating: 5,
    duration: "5 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 299,
  },
  {
    id: "fam-08",
    title: "JUMEIRAH ZABEEL SARAY",
    category: "FAMILY_HOLIDAY",
    shortDesc: "Treat your loved ones to palace-style living inspired by the grandeur of the Ottoman Empire. Features stunning coastal panoramas, cinema rooms, and kids club fun.",
    image: "imgs/holidays/inc/jumeirah-zabeel-saray1.jpg",
    rating: 5,
    duration: "5 Nights",
    features: ["Superior King Room", "Flights included"],
    trustpilotScore: 4,
    price: 1199,
  },
 
];



const lastMinuteHolidaysData = [
  {
    id: "lm-01",
    title: "ICELAND NORTHERN LIGHTS CRUISE",
    category: "Last_Minute_Holidays",
    image: "imgs/holidays/inc/iceland-northern-lights.jpg",
    rating: 5,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 266,
    shortDesc: "Sail out into the dark Icelandic waters for a front-row seat to the spectacular Aurora Borealis. This thrilling last-minute cruise combines dramatic coastal winter scenery with an unforgettable chase for the world's most beautiful natural light show."
  },
  {
    id: "lm-02",
    title: "SIX NATIONS 2022 ENGLAND VS ITALY",
    category: "Last_Minute_Holidays",
    image: "imgs/holidays/inc/six-nations-england-italy.jpg",
    rating: 5,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 499,
    shortDesc: "Experience the electric matchday atmosphere of the historic Six Nations championship with a quick weekend getaway. Perfect for sports fans wanting to witness top-tier rugby action live alongside exploring a vibrant European host city."
  },
  {
    id: "lm-03",
    title: "VENICE HOLIDAY W GONDOLA RIDE",
    category: "Last_Minute_Holidays",
    image: "imgs/holidays/inc/venice-gondola.jpg",
    rating: 5,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 229,
    shortDesc: "Escape on a romantic getaway to the winding canals and historical palaces of Venice. Glide beneath iconic bridges during an authentic gondola ride and lose yourself in the atmospheric cobblestone alleys of this timeless floating city."
  },
  {
    id: "lm-04",
    title: "KRAKOW XMAS W SALT MINE TOUR",
    category: "Last_Minute_Holidays",
    image: "imgs/holidays/inc/krakow-xmas-salt-mine.jpg",
    rating: 5,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 199,
    shortDesc: "Immerse yourself in festive magic at Poland's famous Christmas markets, then head deep underground to explore the majestic, hand-carved Wieliczka Salt Mine. A wonderful winter break filled with cultural heritage and holiday cheer."
  },
  {
    id: "lm-05",
    title: "BUCHAREST W BROWN BEAR SANCTUARY",
    category: "Last_Minute_Holidays",
    image: "imgs/holidays/inc/bucharest-bear-sanctuary.jpg",
    rating: 5,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 299,
    shortDesc: "Blend a dynamic city break in Romania's historic capital with a truly unique wildlife excursion. Travel into the forested hills to visit a sprawling sanctuary dedicated to the protection and preservation of beautiful European brown bears."
  },
  {
    id: "lm-06",
    title: "BUDAPEST CHRISTMAS 2022",
    category: "Last_Minute_Holidays",
    image: "imgs/holidays/inc/budapest-christmas.jpg",
    rating: 5,
    duration: "3 Nights",
    features: ["Flights included"],
    trustpilotScore: 4,
    price: 229,
    shortDesc: "Celebrate the holiday season in style across Budapest's brilliantly illuminated public squares. Sip warm mulled wine, sample local chimney cakes at the artisan stalls, and finish your evenings relaxing inside the city's famous thermal baths."
  }
];







export { cityBreaksData, inclusiveHolidaysData, BeachHolidays ,FamilyHolidays,lastMinuteHolidaysData};