 data: [
      {
        title: "7 Nights 3 Star Umrah Package",
        slug: "7-nights-3-star",
        shortDesc: "A perfectly balanced express itinerary designed for short spiritual getaways.",
        description: "Makkah Hotel: Emaar Al Khalil (4 Nights) | Madinah Hotel: Al Mukhtara International (3 Nights).Fully Inclusive Package (Flights, Meals, Transfers & Ziyarah Guide)",
        star: "STAR_3", type: "NORMAL", 
        month: null, 
        duration: 7,
        makkahHotel: "Emaar Al Khalil", madinahHotel: "Grand Zowar Hotel", price: 675,
      },
      {
        title: "8 Nights 3 Star Umrah Package",
        slug: "8-nights-3-star",
        shortDesc: "Most popular budget itinerary for balanced worship experience.",
        description: "Makkah Hotel: Emaar Andalusia Hotel (4 Nights) | Madinah Hotel: Grand Zowar Hotel (4 Nights) Fully Inclusive Package (Flights, Meals, Transfers & Ziyarah Guide).",
        star: "STAR_3", type: "NORMAL", month: null, duration: 8,
        makkahHotel: "Emaar Andalusia Hotel", madinahHotel: "Grand Zowar Hotel", price: 690,
      },
      {
        title: "9 Nights 3 Star Umrah Package",
        slug: "9-nights-3-star",
        shortDesc: "Extended itinerary for families and senior pilgrims.",
        description: "Makkah Hotel: Emaar Al Khalil Hotel (5 Nights) | Madinah Hotel: Emaar Taibah Hotel (4 Nights) Fully Inclusive Package (Flights, Meals, Transfers & Ziyarah Guide)",
        star: "STAR_3", type: "NORMAL", month: null, duration: 9,
        makkahHotel: "Emaar Al Khalil Hotel", madinahHotel: "Al Eiman Ohud", price: 705,
      },
      {
        title: "10 Nights 3 Star Umrah Package",
        slug: "10-nights-3-star",
        shortDesc: "Two-week spiritual journey at economical price.",
        description: "Makkah Hotel: Emaar Al Khalil Hotel (6 Nights) | Madinah Hotel: Emaar Taibah Hotel (4 Nights) Fully Inclusive Package (Flights, Meals, Transfers & Ziyarah Guide)",
        star: "STAR_3", type: "NORMAL", month: null, duration: 10,
        makkahHotel: "Emaar Al Khalil Hotel", madinahHotel: "Emaar Taibah Hotel", price: 720,
      },
      {
        title: "12 Nights 3 Star Umrah Package",
        slug: "12-nights-3-star",
        shortDesc: "Two-week spiritual journey at economical price.",
        description: "Makkah Hotel: Emaar Al Khalil Hotel (6 Nights) | Madinah Hotel: Elaf Taiba Hotel (6 Nights) Fully Inclusive Package (Flights, Meals, Transfers & Ziyarah Guide)",
        star: "STAR_3", type: "NORMAL", month: null, duration: 12,
        makkahHotel: "Emaar Al Khalil Hotel", madinahHotel: "Elaf Taiba Hotel", price: 760,
      },
      {
        title: "14 Nights 3 Star Umrah Package",
        slug: "14-nights-3-star",
        shortDesc: "Two-week spiritual journey at economical price.",
        description: "Makkah Hotel: Emaar Al Khalil Hotel (7 Nights) | Madinah Hotel: Emaar Taibah Hotel (7 Nights) Fully Inclusive Package (Flights, Meals, Transfers & Ziyarah Guide)",
        star: "STAR_3", type: "NORMAL", month: null, duration: 14,
        makkahHotel: "Emaar Al Khalil Hotel", madinahHotel: "Emaar Taibah Hotel", price: 780,
      },
    ],