// ─────────────────────────────────────────────
//  HOLIDAYS DATA — shared across all sections
// ─────────────────────────────────────────────

export const mostSearched = [
  {
    slug: "dubai",
    destination: "Dubai, UAE",
    title: "Dubai Luxury Escape",
    days: 5,
    nights: 4,
    price: "£804",
    originalPrice: "£1,200",
    rating: 4.9,
    reviews: 2840,
    hotel: "Burj Al Arab, 5★",
    food: "Breakfast Included",
    image: "/imgs/holidays/dubai.jpg",
    tag: "🔥 Trending",
    amenities: ["Free WiFi", "Airport Transfer", "City Tour"],
    badge: "Most Booked",
    color: "#F6931F",
  },
  {
    slug: "maldives",
    destination: "Malé, Maldives",
    title: "Maldives Overwater Bliss",
    days: 7,
    nights: 6,
    price: "£1,290",
    originalPrice: "£1,800",
    rating: 5.0,
    reviews: 1560,
    hotel: "Conrad Maldives, 5★",
    food: "All Inclusive",
    image: "/imgs/holidays/maldives.jpg",
    tag: "✨ Exclusive",
    amenities: ["Private Beach", "Snorkeling", "Spa Access"],
    badge: "Top Pick",
    color: "#0070A1",
  },
  {
    slug: "paris",
    destination: "Paris, France",
    title: "Paris Romantic Getaway",
    days: 6,
    nights: 5,
    price: "£620",
    originalPrice: "£940",
    rating: 4.8,
    reviews: 3210,
    hotel: "Le Marais Boutique, 4★",
    food: "Bed & Breakfast",
    image: "/imgs/holidays/paris.jpg",
    tag: "💞 Romantic",
    amenities: ["Seine Cruise", "Eiffel Tour", "Museum Pass"],
    badge: "Best Value",
    color: "#e83e8c",
  },
];

export const popularHolidays = [
  {
    slug: "spain",
    destination: "Barcelona, Spain",
    title: "Spain Costas & Culture",
    days: 7,
    nights: 6,
    price: "£345",
    originalPrice: "£520",
    rating: 4.7,
    reviews: 1890,
    hotel: "Hotel Arts Barcelona, 5★",
    food: "All Inclusive",
    image: "/imgs/holidays/spain.jpg",
    tag: "🌊 Beach",
    amenities: ["Beach Access", "Water Sports", "Nightlife"],
    badge: "Fan Favourite",
    highlight: "Gaudí Architecture Tour",
  },
  {
    slug: "greece",
    destination: "Athens & Santorini, Greece",
    title: "Greece Islands & Culture",
    days: 8,
    nights: 7,
    price: "£450",
    originalPrice: "£680",
    rating: 4.9,
    reviews: 2120,
    hotel: "Canaves Oia Suites, 5★",
    food: "Half Board",
    image: "/imgs/holidays/greece.jpg",
    tag: "🏛️ Cultural",
    amenities: ["Island Hopping", "Wine Tasting", "Sunset Cruise"],
    badge: "Editor's Choice",
    highlight: "Santorini Caldera Views",
  },
  {
    slug: "turkey",
    destination: "Istanbul & Cappadocia, Turkey",
    title: "Turkey: Two Worlds Tour",
    days: 9,
    nights: 8,
    price: "£520",
    originalPrice: "£790",
    rating: 4.8,
    reviews: 1740,
    hotel: "Ciragan Palace Kempinski, 5★",
    food: "Breakfast Included",
    image: "/imgs/holidays/turkey.jpg",
    tag: "🎈 Adventure",
    amenities: ["Hot Air Balloon", "Bosphorus Cruise", "Bazaar Tour"],
    badge: "Hidden Gem",
    highlight: "Balloon Ride at Sunrise",
  },
  {
    slug: "bali",
    destination: "Bali, Indonesia",
    title: "Bali Serenity Retreat",
    days: 10,
    nights: 9,
    price: "£780",
    originalPrice: "£1,100",
    rating: 4.9,
    reviews: 2450,
    hotel: "Four Seasons Jimbaran, 5★",
    food: "All Inclusive",
    image: "/imgs/holidays/bali.jpg",
    tag: "🌿 Wellness",
    amenities: ["Yoga & Spa", "Temple Tours", "Rice Terrace Hike"],
    badge: "Wellness Pick",
    highlight: "Ubud Jungle Retreat",
  },
];

export const otherPackages = [
  {
    slug: "new-york",
    destination: "New York, USA",
    title: "NYC City Pulse",
    days: 6,
    nights: 5,
    price: "£890",
    originalPrice: "£1,300",
    rating: 4.7,
    reviews: 1320,
    hotel: "The Plaza Hotel, 5★",
    food: "Room Only",
    image: "/imgs/holidays/newyork.jpg",
    icon: "🗽",
    amenities: ["Broadway Show", "Central Park Tour", "Statue of Liberty"],
  },
  {
    slug: "japan",
    destination: "Tokyo & Kyoto, Japan",
    title: "Japan Cherry Blossom Tour",
    days: 11,
    nights: 10,
    price: "£1,150",
    originalPrice: "£1,600",
    rating: 5.0,
    reviews: 980,
    hotel: "Park Hyatt Tokyo, 5★",
    food: "Breakfast Included",
    image: "/imgs/holidays/japan.jpg",
    icon: "⛩️",
    amenities: ["Ryokan Stay", "Tea Ceremony", "Mount Fuji Day Trip"],
  },
  {
    slug: "morocco",
    destination: "Marrakech, Morocco",
    title: "Morocco Desert & Medina",
    days: 7,
    nights: 6,
    price: "£390",
    originalPrice: "£580",
    rating: 4.6,
    reviews: 1450,
    hotel: "La Mamounia, 5★",
    food: "Bed & Breakfast",
    image: "/imgs/holidays/morocco.jpg",
    icon: "🏜️",
    amenities: ["Sahara Camel Trek", "Hammam Spa", "Souk Shopping"],
  },
  {
    slug: "singapore",
    destination: "Singapore",
    title: "Singapore: City of Wonder",
    days: 5,
    nights: 4,
    price: "£720",
    originalPrice: "£1,050",
    rating: 4.8,
    reviews: 1670,
    hotel: "Marina Bay Sands, 5★",
    food: "Breakfast Included",
    image: "/imgs/holidays/singapore.jpg",
    icon: "🌆",
    amenities: ["Infinity Pool", "Gardens by Bay", "Universal Studios"],
  },
  {
    slug: "kenya",
    destination: "Nairobi & Maasai Mara, Kenya",
    title: "Kenya Wildlife Safari",
    days: 8,
    nights: 7,
    price: "£1,400",
    originalPrice: "£2,000",
    rating: 5.0,
    reviews: 760,
    hotel: "Angama Mara Lodge, 5★",
    food: "Full Board",
    image: "/imgs/holidays/kenya.jpg",
    icon: "🦁",
    amenities: ["Big Five Safari", "Balloon Safari", "Maasai Village"],
  },
  {
    slug: "italy",
    destination: "Rome & Amalfi, Italy",
    title: "Italian Dolce Vita Tour",
    days: 9,
    nights: 8,
    price: "£680",
    originalPrice: "£970",
    rating: 4.9,
    reviews: 2100,
    hotel: "Hotel de Russie, 5★",
    food: "Half Board",
    image: "/imgs/holidays/italy.jpg",
    icon: "🍝",
    amenities: ["Colosseum Tour", "Amalfi Coastal Drive", "Wine & Dine"],
  },
];